tasks:
  - id: design_task
    description: >
      Analyze the user prompt, categorize the website type,
      suggest relevant pages, search for similar websites, and design using Elementor.
    expected_output: >
      A full set of designed Elementor pages based on client input,
      competitive research, and learned best practices.
    agent_id: airodev
